from core.const import CHIP_SIZE


SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 768
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_FPS = 60
FULL_SCREEN = False # not implemented yet
ZOOM = 3

ZOOMED_CHIP = ZOOM * CHIP_SIZE